baseURL = "https://www.gocat.dev/"
languageCode = "ru-ru"
defaultContentLanguage = "ru"
title = 'Go-Котяра - Русскоязычное сообщество Golang'
[media]
  [media."image"]
    [media."image"."resize"]
      quality = 80
[[menu.main]]
  name = "Категории"
  pageRef = "/categories"
  weight = 20
[markup] # Подсветка синтаксиса
  [markup.highlight]
    codeFences = true
    hl_Lines = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = 'github' #, vs, dracula 'github' # или monokai
[params]
  showHeadingAnchors = false
  description = "GoCat - изучение Golang на русском языке. Туториалы, документация, примеры кода и песочница для Go программирования"
  author = "GoCat Team"
  keywords = "golang, go, программирование, обучение, туториалы, документация, русский язык"

