[build]
  command = "git submodule update --init --recursive && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.150.0"
  HUGO_EXTENDED = "true"

[context.production.environment]
  HUGO_ENV = "production"